name: run-script-github
on: 
  workflow_dispatch:
    input:
      enter values:
        dsecription: 'enter values'
        required: true
        default: 1, 2, 20, 30, 100, 3, 50, 4 
env:
  name: myscript.py
  run: ${{github.event.input.entervalues}}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: python --version
      - name: run script
        run:  |
          cd file1
          python $name $run
